### ISSUE TITLE
open roadmap and planning

### ISSUE THREAD

**Issue by michelleN** [cnabio/cnab-spec#163]
We're currently in the process of stabilizing the spec and do updates around priorities during the community meetings but it would also be great to document our timeline/roadmap/priorities somewhere on this repo. 

1. Does anyone know how other specs do this kind of open planning. would love to leverage prior art here?
2. Does anyone have suggestions on how we should go about doing this? Would a document be sufficient? Should we use project boards and milestones?

**Comment by youreddy** [comment]
I think this is great idea! I don't have specific examples to point to but I looked into [github project boards](https://help.github.com/en/articles/about-project-boards) and it seems like it could work well for us. I like the idea of creating an organization wide project board so that we can create cards that reference duffle, porter and other repositories related to the spec.

**Comment by GreenCee** [comment]
Firecracker just posted their 2020 roadmap RFC as part of an issue. Sharing that view of the next things coming up drove clarity of what to expect out of 175+ open issues

https://github.com/firecracker-microvm/firecracker/issues/1104

**Comment by technosophos** [comment]
I am closing this issue, as the spec for CNAB Core 1.0 is done, and milestones are used to track what is one the roadmap. Feel free to re-open if you have a concrete proposal
