### ISSUE TITLE
What is the default platform for an invocation image?

### ISSUE THREAD

**Issue by simongdavies** [cnabio/cnab-spec#179]
The spec defines that an invocation [image can optionally include a platform  object](https://github.com/deislabs/cnab-spec/blob/master/101-bundle-json.md#invocation-images) specifying the os and architecture for the image. I cannot find anywhere that specifies what the default value is if these are not specified (implicitly it seems to be os==linux and architecture==x86-64) should these values be explicitly defined? Should they be different for different invocation imageTypes?

**Comment by carolynvs** [comment]
Seems like not just the defaults but the set of values would be best to put in the spec as well, no? Otherwise there are many different tags that could be used to specify an OS or ARCH, and I think in the examples given so far, we are assuming the terms used by Go. It would help to say what we are following so that people know where the list of acceptable values are coming from.

**Comment by simonferquel** [comment]
Related to that, I added #185. I think it is confusing, as the image referenced can itself be a multi-arch image.

**Comment by simonferquel** [comment]
(and even if it is not, the os/arch can be inferred on inspecting the image manifest)

**Comment by technosophos** [comment]
For naming conventions, I was following the arch and OS defined by Docker, which are consistent with the ones used by Go.

The intention of this section was to make it possible to differentiate multiple images _to a user_. So in that sense, `platform` was really more like a set of convenient labels so that they could tell why there were multiple invocation images. Originally, we had talked about making these arbitrary name/value pairs, but it ended up just being `os` and `arch` (I can't remember why).

The goal was never really to make this a machine-read value. In most cases, the agent can detect the image type (at least after a pull). And when you think about the VM case, OS and Arch are actually not important at all.

So... (a) there's no real sense in which there are "default" values to this, but also (b) in light of #185, maybe we should just convert this to free-form labels.

The idea, then, would be that a user could do:

``` console
$ cnabtool --list-invocation-images foo
0 - linux amd64
1 - windows amd64
2 - linux arm32
$ cnabtool --install --use-image=2 foo
```

(Or something like that)

**Comment by simongdavies** [comment]
OK this makes sense. I think that there is an issue in duffle though as the driver interface does not pass information about the platform\arch and there are cases where the driver is capable of invoking images using different platforms and arches (e.g. kubernetes, ACI etc.) I will open an issue over there

**Comment by technosophos** [comment]
I am closing this, since it does not appear that there is remaining work here for the spec. Feel free to re-open if I misunderstood.
