### ISSUE TITLE
$ref value "http://cnab.io/v1/definitions.schema.json" returns 404

### ISSUE THREAD

**Issue by mikekillam1952** [cnabio/cnab-spec#284]
Lines 217 - 222 of the cnab-spec/schema/bundle.schema.json contains:

217    "definitions": {
218      "additionalProperties": {
219        "$ref": "http://cnab.io/v1/definitions.schema.json"
220      },
221      "type": "object"
222   },

The $ref value "http://cnab.io/v1/definitions.schema.json" is causing a 404 'not found' failure in code (go) used to verify that a payload (JSON) meets the CNAB specification requirements.  

If I enter "http://cnab.io/v1/definitions.schema.json" as a URL in a web browsers, the cnab.io home page is displayed, with a 404 'not found' message.
 
If I replace line 219 with:
"$ref": "http://json-schema.org/draft-07/schema#/definitions"

The validation code works correctly.

**Comment by carolynvs** [comment]
We don't use http://json-schema.org/draft-07/schema#/definitions because we use canonical json, which disallows numbers, only integer values are supported.

We have an [open issue](https://github.com/deislabs/cnab.io/issues/15) to host the schema on cnab.io with some good ideas for now to implement it. Sounds like we need to bump that up in priority. 

Thanks for letting us know that it is breaking validators!

**Comment by technosophos** [comment]
A stop-gap would be to use this URL:

https://raw.githubusercontent.com/cnabio/cnab-spec/cnab-core-1.0/schema/definitions.schema.json
