### ISSUE TITLE
Does the claims spec provide enough specification? 

### ISSUE THREAD

**Issue by jeremyrickard** [cnabio/cnab-spec#313]
>However, this specification describes how a CNAB-based system MUST emit the record to an invocation image, and provides some guidance on maintaining integrity of the system.

> This is done so that implementors can standardize on a way of relating a release claim (the record of a release) to release operations like install, upgrade, or uninstall. This, in turn, is necessary if CNAB bundles are expected to be executable by different implementations.

I'm curious how the claim system is intended to be used between actions on a bundle. Suppose a bundle does an installation, which produces output X. Then an upgrade (with a different bundle version) adds an output Y. I think the claims spec under specifies what the expected behavior is right now. 

Porter has this issue open right now: https://github.com/deislabs/porter/issues/836

Is this a bad interpretation of the spec? Or is this a bug and the spec under specifies what should happen? I think we should update the claim spec to be explicit about the behavior compliant runtimes should provide.

**Comment by technosophos** [comment]
It appears that you want to do things with output that the claims spec was not designed for. Claims were not supposed to be persistent data stores for arbitrary data. They were supposed to be a record of what the last operation on an installation was. It appears that what you (and possibly the rest of the Porter authors) want is a way to access outputs across multiple operations. In other words, you want the outputs for installation at T to persist after an upgrade at T+1, and made available to the subsequent upgrade at T+2.

But that's not what a claim is designed for. It is designed to tell you at T+2 what happened at T+1. You can, of course, store a claim for each operation (like Helm does) so that at T+2 you can see what happened at T+1 and at T. But it doesn't sound like that's really want you want either. So I am guessing that you are after #327.

See #329 and #327

**Comment by vdice** [comment]
The Claim spec has since been updated in many areas, including the [outputs](https://github.com/cnabio/cnab-spec/blob/master/400-claims.md#outputs) section particular to this issue.  While it still doesn't prescribe _how_ a tool might persist outputs across actions (though, if interested, [Porter](https://github.com/getporter/porter) does so), the spec does allow for this functionality by specifying that output names (and optionally, their content digests), be added to each [claim result](https://github.com/cnabio/cnab-spec/blob/master/400-claims.md#claim-results).  Since claim results are required to be recorded for every operation associated with a final status (e.g. succeeded or failed), tools thus have the framework for persisting outputs.

Closing per the above updates, but feel free to re-open if there are any remaining concerns.  Note that we are attempting to wrap up the first [1.0.0 release](https://github.com/cnabio/cnab-spec/milestone/5) of the Claims spec soon.
