### ISSUE TITLE
Spec is contradictory on how string-type parameter values are encoded

### ISSUE THREAD

**Issue by corhere** [cnabio/cnab-spec#316]
The [Setting Parameter Values section of the bundle runtime spec](https://github.com/cnabio/cnab-spec/blob/master/103-bundle-runtime.md#setting-parameter-values) seems to contradict itself. The parameter value evaluation rules state (#269) 
> Values are encoded as JSON strings.

But the examples in the section do not seem to follow this rule. The `path` destination example states that the `/var/run/greeting.txt` file would be created with contents `hello`, which is not well-formed JSON text. By my reading of the rules, the file should instead have the contents `"hello"`. Which is the correct behavior? Are the rules incomplete, or are the examples incorrect?

**Comment by carolynvs** [comment]
In practice, the CNAB tools do not marshal every parameter as json. I often reference this PR to the cnab-go library to understand what is marshaled and how. 

https://github.com/cnabio/cnab-go/pull/96/files

**Comment by corhere** [comment]
I see that the spec does not use any MUST, REQUIRED or SHALL language for the value encoding, so cnab-go is free to deviate from the encoding rule (encoding string parameter values as UTF-8) while still technically being in compliance with CNAB Core 1.0. But this also allows for other compliant CNAB runtimes to encode parameter values differently, which could be troublesome for interoperability. If some CNAB runtimes encode string parameters as UTF-8, others as UTF-16LE and yet more as JSON documents, it would be a nightmare for a bundle author to support all of those encodings.

Would this be sufficient justification to warrant codifying cnab-go's behavior for string parameters into the spec, either as an erratum for CNAB Core 1.0 or added to CNAB Core 1.1? I am interested in contributing to the specification and would be happy to take this on.

**Comment by technosophos** [comment]
I am not totally sure how to interpret that line of the spec. I was under the impression that what it meant was that values are to be encoded using the JSON specification's definition of `string` (e.g. for escaping characters and such). But the suggestions here are that it means "values are to be inlined JSON documents."

The PR that @carolynvs referenced seems to confirm the later reading... sorta... except for cases where the JSON output ends up being `"some string"`. The original issue, though, suggests that what we are after is for a standard serialization for NON-primitive types: https://github.com/cnabio/cnab-spec/issues/250

So do we think the intended wording of the spec should have been: 

> Values MUST be strings, and complex data structures SHOULD be encoded as strings by serializing them to JSON and escaping the resulting data as a JSON string.

For example, the pseudo-code value

```
struct {
  string foo: "hello"
}
```

should be serialized to

```json
{foo: "hello"}
```

And then injected into the document as

"{foo: \"hello\"}"

I'm not entirely sure that we really need to insist that values be presented as strings, since the consumer of the values is undetermined by the spec. I think we were just shooting for increased interoperability.

If possible, we should try to fix this in the next week so that it can make it into the 1.0.1 specification.

**Comment by carolynvs** [comment]
This makes sense to me and clears up how to treat primitive types. 👍 Really as you said it's up to the parameter consumer, the runtime doesn't care.

**Comment by chris-crone** [comment]
I agree with Matt's reading and clarification of this for non-primitive types.

The other issue raised by @corhere is about character encoding for the mounted parameter file. To this I would add line endings as a possible problem too. We could amend:
> In the case where the destination object has a path field, the CNAB runtime MUST create a file at that path. The file MUST have sufficient permissions that the effective user ID of the image can read the contents of the file. And the contents of the file MUST be the parameter value (calculated according to the rules above).

To be (additions italicised):
> In the case where the destination object has a path field, the CNAB runtime MUST create a file at that path. The file MUST have sufficient permissions that the effective user ID of the image can read the contents of the file. _The file's character encoding SHOULD be UTF-8 and new lines SHOULD be LF (line feed)._ And the contents of the file MUST be the parameter value (calculated according to the rules above).

I chose _SHOULD_ here as this would not be natural for non-UNIX systems. I chose not to say POSIX as that adds requirements like an empty line at the end of the file.
