### ISSUE TITLE
Claim result message

### ISSUE THREAD

**Issue by itaysk** [cnabio/cnab-spec#57]
As I understand, a claim `result.message` is the entire stdout of the invocation image (BTW, this should be written more clearly). 
This design has a few issues:
1. stdout is conventionally used more loosely to communicate with the user. Restricting stdout to a concise message feels unnatural.
2. It's not always easy to control what's being written by other tools. The sample redirects every command to `/dev/null` which is cumbersome and error prone.
3. Concise result message and informative progress visibility are two desirable facilities. The developer shouldn't be force to sacrifice one for the other.

I suggest to leave stdout to be (runtime developers may offer a method to retrieve it), and have developer craft the result message in a designated variable or file.

Additionally, I think it's useful to include the exit code as a field in the result, as it's already mandated by the spec.

**Comment by technosophos** [comment]
Where would this message come from?

And which exit code? The exit of the invocation image? Or of something inside of the invocation image?

Our main issue with returning information is that there is no native facility for message passing between a container and the container's runtime environment. Basically, we're limited to STDOUT and STDERR, with the potential option of attaching files to at least some image runtimes. Adding anything else seems to incur some overhead on the package creator (the user who creates the package), since they will be responsible for implementing... something.

We've been talking about whether mounting a read/write volume to the invocation image would provide us with a way to do this. But that will place a new requirement on the runtime: that both the "client" end and the "invocation image" end can read/write from this location.

We've also talked about using structured output (e.g. JSON log messages or something) piped over STDOUT from the run tool. This imposes some burden on the run tool (our simple shell script would no longer suffice, for example). But this seems like perhaps the least intrusive channel back. In that case, we could reserve a key in that structure for setting `result.message`.

**Comment by itaysk** [comment]
For exit code:
IMO should be the exit code of the invocation image, which is controlled by the image developer or takes the exit code of the contained command (unless the container runtime had an error).

For communicating result message:
At my prev workplace they solved a similar issue by mounting a volume which was the easiest solution. I could agree it adds a level of complexity however volume mount is already included in the spec for secret injection.
Maybe another option for file based comm is the container writes to local file predefined by the spec (like `/cnab/app/result/message`), and the runtime extracts it from the exited container e.g using `docker cp`.
(I don't see how structuring the output resolves the concerns raised about repurposing stdout)

**Comment by technosophos** [comment]
Okay, I'll look into these ideas.

Our complicating factor is that not all invocation images will execute on a local Docker daemon. Some will execute remotely (inside of Kubernetes or server-hosted container runtimes like those provided by Azure and Amazon) or even virtual machines. So the solution has to be generic enough to handle those cases. But mounting filesystems might be the most straightforward way of doing that.

**Comment by technosophos** [comment]
Okay, the current proposal for this is now at #133. Feedback would be welcome.

**Comment by itaysk** [comment]
#133 is a great addition, but I don't think it really addressed the concerns raised here. We might close this one given there's no clearly superior solution, but just wanted make sure we understand it's more like abandoned then solved.

**Comment by technosophos** [comment]
No solution has been proposed in the last year, so I am marking this as closed. Feel free to re-open with a proposal.
